name = "ewdev/multitarget"
version = "0.4.2-rc.7"
description = "[Fork] Customizable and flexible build script for multiple pesde targets"
authors = ["jiwonz <me@jiwonz.kr>", "EwDev (https://ewdev.net/)"]
repository = "https://github.com/ewd3v/pesde-multitarget"
license = "MIT"
includes = ["src/**", "LICENSE", "README.md", "pesde.toml"]

[target]
environment = "lune"
lib = "src/lib.luau"
bin = "src/bin.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
example = "scripts/example.luau"

[engines]
lune = "^0.10.3"
pesde = "^0.7.1"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0" }
greentea = { name = "jiwonz/greentea_luau", version = "^0.2.0", target = "luau" }
argparse = { name = "caveful_games/argparse", version = "^0.1.2" }
glob = { name = "jiwonz/glob", version = "^0.2.0" }
darklua_lune = { name = "jiwonz/darklua_lune", version = "^0.3.0" }
result = { name = "lukadev_0/result", version = "^1.2.1" }
chalk_luau = { name = "kimpure/chalk_luau", version = "^0.1.8", target = "luau" }
luau_path = { name = "jiwonz/luau_path", version = "^0.2.0", target = "luau" }
